version: '3.7'
services:
  mysql:
    image: mysql:8.0
    volumes:
      - ./service/mysql/config/mysqld.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./service/mysql/data:/var/lib/mysql/:rw
      - ./service/mysql/log/:/var/log/mysql/:rw
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  php-fpm-7-3:
    image: php:7.3-fpm
    volumes:
      - ./www/:/var/www/html/
      - ./service/php7.3/config/php.ini:/usr/local/etc/php/php.ini:ro
      - ./service/php7.3/config/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - mysql
    links:
      - mysql:mysql
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www/:/usr/share/nginx/html/:rw
      - ./service/nginx/config:/etc/nginx/conf.d/
      - ./service/nginx/log/:/var/log/nginx/:rw
    depends_on:
      - php-fpm-7-3
    links:
      - php-fpm-7-3:php-fpm-7-3
#  redis:
#    image: redis:latest
#    ports:
#      - "6379:6379"
#    volumes:
#      - $PWD/service/nginx/config/:/usr/local/etc/redis/
  composer:
    image: composer
    volumes:
      - ./www/:/app
    depends_on:
      - php-fpm-7-3
