version: '3.7'
services:
  mysql:
    build: ./mysql5.6
    volumes:
      - ./service/mysql/config/mysqld.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./service/mysql/data:/var/lib/mysql/:rw
      - ./service/mysql/log/:/var/log/mysql/:rw
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  php-fpm:
    build: ./php5.4/
    volumes:
      - ./www/:/var/www/html/
      - ./service/php7.2/config/php.ini:/usr/local/etc/php/php.ini:rw
      - ./service/php7.2/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - mysql
    links:
      - mysql:mysql
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www/:/usr/share/nginx/html/:rw
      - ./service/nginx/config:/etc/nginx/conf.d/
      - ./service/nginx/log/:/var/log/nginx/:rw
    depends_on:
      - php-fpm
    links:
      - php-fpm:php-fpm
